# Generated by Django 5.2.6 on 2025-10-22 04:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('file_name', models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Viewed', 'Viewed'), ('Reviewed', 'Reviewed')], default='Waiting', max_length=20)),
                ('ai_confidence', models.FloatField(default=0, help_text='AI detection confidence (0-100)')),
                ('ai_risk_level', models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='Very Low', max_length=20)),
                ('ai_indicators', models.TextField(blank=True, help_text='AI detection indicators')),
                ('is_ai_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'Lecturer'}, on_delete=django.db.models.deletion.CASCADE, to='plag.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plag.upload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['student'], name='plag_upload_student_80ef21_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['lecturer'], name='plag_upload_lecture_8738ed_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['status'], name='plag_upload_status_b3384d_idx'),
        ),
    ]
